services:
  lua-ls:
    build:
      context: ./docker
    volumes:
      - .:$PWD
    working_dir: $PWD
    command: /app/bin/lua-language-server
  node-tools:
    build:
      context: ./docker
      dockerfile: Dockerfile.node
    volumes:
      - $HOME:$HOME
    ports:
      - "1455:1455"
    working_dir: $HOME
    stop_grace_period: 1s
    command: tail -f /dev/null
