#!/usr/bin/env zsh

if [ ! -d ~/.oh-my-zsh ]; then
  curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh
fi

cd `dirname $0`
DOTFILES=$(pwd)

echo "export DOTFILES=${DOTFILES}" > ~/.dotfiles
cat ~/.zshrc | grep "\.dotfiles" || echo ". ${HOME}/.dotfiles" > ~/.zshrc
cat ~/.zshrc | grep "DOTFILES/zshrc" || echo 'source $DOTFILES/zshrc' >> ~/.zshrc
[ $USER = key ] && cat ~/.zshrc | grep 'DOTFILES/zshrc.key' || echo 'source $DOTFILES/zshrc.key' >> ~/.zshrc
cat ~/.gitconfig | grep include || echo "[include]\n\tpath = ${DOTFILES}/gitconfig" >> ~/.gitconfig
[ -f ~/.gitignore ] || cp $DOTFILES/gitignore ~/.gitignore
[ -d ~/.bin] || mkdir ~/.bin

source ~/.zshrc

if [ ! -f ~/.vim/autoload/plug.vim ]; then
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  nvim +PlugInstall +qa
fi

[ -d ~/.config/nvim ] || mkdir -p ~/.config/nvim
cat ~/.config/nvim/init.vim | grep $DOTFILES/neo.vim || echo "source ${DOTFILES}/neo.vim" > ~/.config/nvim/init.vim
